# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/tylere-blog',
                'doc_host': 'https://tylere.github.io',
                'git_url': 'https://github.com/tylere/tylere-blog',
                'lib_path': 'tylere_blog'},
  'syms': {'tylere_blog.core': {'tylere_blog.core.foo': ('core.html#foo', 'tylere_blog/core.py')}}}