name: Deploy to GitHub Pages
on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:
  schedule:
    # Runs "at every 10 minutes" (see https://crontab.guru)
    - cron: '*/10 * * * *'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Write Earth Engine credentials file
        run: |
          mkdir -p /home/runner/.config/earthengine
          echo ${{ secrets.SECRET_CREDENTIALS }} | base64 --decode > /home/runner/.config/earthengine/credentials
      - uses: fastai/workflows/quarto-ghp@master
        with: {pre: 1}