name: CI
on:  [workflow_dispatch, pull_request, push]

jobs:
  test:
    environment: CI
    runs-on: ubuntu-latest
    steps: 
      - name: Write Earth Engine credentials file
        run: |
          echo "DEBUG_test"
          mkdir -p /home/runner/.config/earthengine
          echo ${{ secrets.SECRET_CREDENTIALS_JSON }} | base64 --decode > /home/runner/.config/earthengine/private-key.json
      - uses: fastai/workflows/nbdev-ci@master