name: CI
on:  [workflow_dispatch, pull_request, push]
jobs:
  test:
    environment: CI
    runs-on: ubuntu-latest
    env:
      GEE_PRIVATE_KEY: /home/runner/.config/earthengine/private-key.json
    steps: 
      - name: Write Earth Engine credentials file
        run: |
          mkdir -p /home/runner/.config/earthengine
          echo ${{ secrets.SECRET_CREDENTIALS_JSON }} | base64 --decode > $GEE_PRIVATE_KEY
      - uses: fastai/workflows/nbdev-ci@master